name: Ultimos test dom1-d1 

on:
  push:
    branches: 
      - "main"
    paths:
      - "ultimos ejercicios/Dominio 1/desafio 1/src/**"
  pull_request:
    branches: 
      - "main"
    paths:
      - "ultimos ejercicios/Dominio 1/desafio 1/src/**.py"

jobs:
