# .github/workflows/debug-outputs.yml
name: Debugging Outputs
on: workflow_dispatch

jobs:
  producer:
    runs-on: ubuntu-latest
    outputs:
      # La definición del output está mal aquí
      result: steps.set_result.output.result_value
    steps:
      - id: set_result
        run: echo "result_value=hello-world" >> $GITHUB_OUTPUT

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: Use the output
        run: echo "The value from producer is: ${{ needs.producer.outputs.result }}"
