# .github/workflows/debug-deployment.yml
name: Debug Protected Deployment
on:
  push:
    branches:
      - 'feature/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    enviroment: name: production # El entorno 'production' requiere aprobación
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: echo "Deploying to production..."
