# .github/workflows/debug-cache-invalidation.yml
name: Debugging Cache Invalidation
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # El problema está en la configuración de este paso
      - name: Cache pip dependencies
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # Este paso está mal configurado
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run script
        run: python -c "import pandas; print('Pandas importado')"
