name: Debug Reusable Caller
on: workflow_dispatch

jobs:
  call-and-use:
    uses: ./.github/workflows/reusable-debug.yml
    with:
      version: 1.2.3

  deploy:
    runs-on: ubuntu-latest
    needs: call-and-use
    steps:
      - run: echo "Deploying build ${{ needs.call-and-use.outputs.build-id }}"
