# .github/workflows/debug-org-secrets.yml
name: Debug Organization Secrets
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Organization Secret
        run: |
          if [ -z "${{ secrets.NON_EXISTENT_SECRET }}" ]; then
            echo "El secreto no está disponible."
            exit 1
          else
            echo "Secreto encontrado."
          fi
