# .github/workflows/debug-secret-access.yml
name: Debug Organization Secret Access
on:
  workflow_dispatch:

jobs:
  connect-to-db:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Database
        env:
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          echo "Intentando conectar a la base de datos..."
          if [ -n "$DB_PASSWORD" ]; then
            echo "Conexión exitosa (simulada)."
          else
            echo "Fallo de conexión: la contraseña de la BD no fue encontrada."
            exit 1
          fi
