# .github/workflows/debug-secret-syntax.yml
name: Debug Secret Syntax
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Attempt to use secret
        # Prerrequisito: Un secreto llamado `API_KEY` debe existir en el repo.
        run: echo "La clave de API es $API_KEY"
        env:
          API_KEY: ${{ secret.API_KEY }}
