name: Depuración de Trigger Fallido

on:
  push:
    branches-ignore:
    # https://docs.github.com/es/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
      - 'main' # Esto es un error intencional, no funcionará como se espera para "no main"

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run: echo "Esta rama es: ${{ github.ref }}"