name: Despliegue en multi stage

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Relleno
        run: echo "Este step no hace nada realmente"
  staging:
    environment: staging
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4
      - name: Hacer despliegue en ${{ vars.ETAPA }}
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: bash deploy.sh ${{ vars.ETAPA }}
  production:
    environment: "production"
    runs-on: ubuntu-latest
    needs: [build, staging ]
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v4
      - name: Hacer despliegue en ${{ vars.etapa }}
        working-directory: "D1-05-CI-CD-Publishing/desafio 2/"
        run: bash deploy.sh ${{ vars.etapa }}